# config/homenexus.ini

[openweather]
apiKey=
baseUrl=https://api.openweathermap.org
units=metric
language=en
city=Ulm
countryCode=DE
requestTimeoutMs=5000
currentWeatherUpdateIntervalMs=600000
forecastUpdateIntervalMs=1800000